# Generated by Django 4.1.1 on 2022-09-29 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cource_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500)),
                ('question2', models.ImageField(blank=True, upload_to='static/')),
                ('ans', models.IntegerField()),
                ('ontion_1', models.CharField(max_length=250)),
                ('ontion_2', models.CharField(max_length=250)),
                ('ontion_3', models.CharField(blank=True, max_length=250)),
                ('ontion_4', models.CharField(blank=True, max_length=250)),
                ('cource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
    ]
