# Generated by Django 4.1.1 on 2022-09-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cource_question_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ontion_1',
            new_name='option_1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ontion_2',
            new_name='option_2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ontion_3',
            new_name='option_3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='ontion_4',
            new_name='option_4',
        ),
    ]
